# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetFit' do
  pod 'Stripe', '~> 14.0.0'
  inherit! :search_paths
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end
